name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Python Tests
        run: |
          pip install flake8 pytest
          pytest
          flake8
      - name: Build
        run: |
          make
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: factoriostatsd.zip
          path: factoriostatsd.zip
